language: python

python:
  - "2.7"

install:
  - "pip install -r requirements.txt"
  - "pip install -r dev-requirements.txt"

script:
  - "py.test"

after_success:
  - "coveralls"

notifications:
  email: false

sudo: false
